In [16]:
from sklearn.datasets import load_iris
from sklearn.decomposition import PCA
from sklearn.metrics import accuracy_score
import numpy as np

In [17]:
iris=load_iris()
pca=PCA()

In [18]:
x=iris.data

In [19]:
b_cov=np.cov(x.T)
print(f"Covariance before PCA is:\n{b_cov}")

Covariance before PCA is:
[[ 0.68569351 -0.042434    1.27431544  0.51627069]
 [-0.042434    0.18997942 -0.32965638 -0.12163937]
 [ 1.27431544 -0.32965638  3.11627785  1.2956094 ]
 [ 0.51627069 -0.12163937  1.2956094   0.58100626]]


In [20]:
x_p=pca.fit_transform(x)

In [21]:
a_cov=np.cov(x_p.T)
print(f"Covarinace after PCA is :\n{a_cov}")

Covarinace after PCA is :
[[ 4.22824171e+00  2.15308755e-14  2.78971477e-15 -5.71578579e-15]
 [ 2.15308755e-14  2.42670748e-01 -1.77039591e-15 -6.44898005e-16]
 [ 2.78971477e-15 -1.77039591e-15  7.82095000e-02 -3.96774336e-15]
 [-5.71578579e-15 -6.44898005e-16 -3.96774336e-15  2.38350930e-02]]


In [33]:
eigen_val,eigen_vec=np.linalg.eig(a_cov)

In [39]:
explained_variance_ratio=pca.explained_variance_ratio_
cum_variance=np.cumsum(explained_variance_ratio)
opt_comp=np.argmax(cum_variance>=0.95)+1
print(f"The optimum no of compenents is {opt_comp}")

The optimum no of compenents is 2
